version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=14336"
    ENDPOINT_SCHEMA_LAMBDA: "false"
    PROJECT_NAME: "Postman/Newman"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the INSTALL phase...
      - APP_DIR=`pwd`
  build:
    commands:
      - echo Installing source NPM dependencies...
      - env
      - echo `pwd`
      - npm config set unsafe-perm true
      - npm install
  post_build:
    commands:
      - ERROR=0
      - |
        ENV="$ENV_STAGE"
        echo $ENV
        echo Targeted collection $QA_API_TESTS
        COMMAND="node src/index.js --env=$ENV_STAGE --collection=$QA_API_TESTS"
        eval $COMMAND || ERROR=1
        echo ERROR $ERROR
      - echo ERROR STATE AT THE END IS... $ERROR
      - echo $?
      - exit $ERROR

artifacts:
  files:
    - "**/*"
